### ISSUE TITLE
pg 27 연관관계 다중성 표시

### ISSUE THREAD

**Issue by java-saeng** [dpj2022/designPattern-java#1]
책 다중성 표시에서 0 또는 그 이상과 1이상 을 제가 이해하는 게 맞는지 확인 부탁드려요

교수와 학생을 예로 들면
0..* 은 1명의 교수는 학생이 없을 수도 있다.

1..* 은 1명의 교수는 무조건 한 명 이상의 학생을 가져야한다. 없어서는 안된다.

즉, 0..* 이랑 1..* 이  is null과 not null 이라는 뜻일까요?

**Comment by lllilllilllilili** [comment]
p28에 기재된 학생과 교수의 관계에서 표기는 교수 1 학생 1.. * 로 되어있지만, 
말씀하신대로 교수 0..* 학생 1..* 이라면 
교수는 0명 혹은 그 이상이 되고,
학생은 1명 혹은 그 이상이 됩니다.
여기서 다대다 연결관계 해석은 교수 한명은 여러 명의 학생을 알고 있고, 학생 여러명은 교수 한명을 알고있다. 
즉, 서로의 관계를 알 고 있는 관계라고 생각합니다~
말씀해주신 null은 0과 다르다고 생각하는데 JPA는 어떤지 모르겠군요.. 아직 JPA를 못봐서
null이랑 비교될 수 있는지는 주말동안 공부해보고 말씀해드리겠습니다.
