### ISSUE TITLE
정적 메서드는 오버라이딩이 안되나요? 

### ISSUE THREAD

**Issue by lllilllilllilili** [dpj2022/designPattern-java#7]
????

**Comment by lllilllilllilili** [comment]
JVM 에 코드가 올라가는 시점이 런타임.

**Comment by java-saeng** [comment]
Overriding and Hiding
https://docs.oracle.com/javase/tutorial/java/IandI/override.html

**Comment by java-saeng** [comment]
https://greedhead.net/what-is-runtime-polymorphism/
컴파일은 소스 코드가 실행 코드로 변환되는 시간
런타임은 실행코드가 실행되기 시작하는 시간

런타임시점에 결정되는 인스턴스 메서드는 "참조되는 객체의 유형"에 따라 호출

컴파일시점에 결정되는 static 메서드는 "참조 유형"에 따른 메서드 호출

이라고 하는데,

자식 클래스에서 만약 부모 클래스와 같은 이름의 static 메서드를 호출하게 되면 자식 클래스의 static 메서드, 부모 클래스의 static 메서드가 있는데 이거는 그냥 참조 유형을 보고 판단하는 것인가?

**Comment by lllilllilllilili** [comment]
올리신 질문 내용 중에 "참조 유형" 에 대해 이해를 잘 못했습니다. 
여기서 컴파일 시점을 가정하고 생각해보면 
java 파일이 javac 컴파일러에 의해서 .class 바이트 코드로 해석되는 과정이 있는데 이 부분이 즉, 로딩되는 시점으로 가정하고 작성해보면,
`static` 키워드가 붙은 시점부터 메소드 뿐만 아니라 필드도 `static` 하게 적용되어야 컴파일이 가능해집니다. 

- child
```java
package chapter.object;

public class Child extends Parent{
    final static String childField = "자식 필드";
    public static void childMethod(){
        System.out.println(parentField);
        System.out.println(childField);
    }

    public static void main(String[] args) {
        new Child().childMethod();
    }
}

```

- parent
```java
package chapter.object;

public class Parent {
    final static String parentField = "부모 필드";
    public static void parentMethod(){
        System.out.println(parentField);
    }
}
```
그래서, static이 붙은 시점에서 컴파일 과정을 거치고 JVM에 클래스 로더에 의해 메모리에 올라가는 시점이라고 보면 될것 같습니다. 
참조 유형을 검색해봤는데... 잘 이해가 안되는군요 ㅜ 
전체 java 파일이 컴파일 되고 로딩되는 워크플로우 하나 첨부합니다.

<img src="https://i.imgur.com/Vy1JC1b.png" alt=""/>

**Comment by java-saeng** [comment]
Q.
static 키워드가 붙은 시점부터 메소드 뿐만 아니라 필드도 static 하게 적용되어야 컴파일이 가능해집니다.

A.
이 부분은 static 메서드에 접근할 수 있는 필드는 static 필드여야합니다.
인스턴스 변수는 static, 인스턴스 메서드 모두 접근 가능한 것으로 알고 있습니다.

Q.
참조 유형?

A.
참조 유형이라는 것은
A1이 A를 현재 상속받는다는 가정 하에, A1이 자식 클래스 A가 부모 클래스입니다.

A a1 = new A1();

입니다. 여기서 A를 참조 유형, A1이 참조되는 객체 유형을 말합니다.




이 문제에 대해서 정리하자면
static 은 Method Area, 인스턴스는 Heap 영역에 저장되어 인스턴스끼리 오버라이딩,
즉, 동적 바인딩을 할 수 없게 되어 오버라이딩이 불가하다 라고 생각을 했습니다.

**Comment by yrkimoffice** [comment]
“정적 메서드는 상속을 통해 오버라이드 되지 않음을 알 수 있다. 이는 정적 메서드를 실행할 때 동적 바인딩을 실행하는 것이 아니고 컴파일할 때 결정된 객체의 타입에 따라 실행될 메서드가 결정된다는 의미다.”  - P.95 상속과 정적 메서드의 관계를 유추하라.

static 메서드는 method overriding 이 아닌 method hiding (은닉)을 수행합니다. 

숨겨진다는 의미는 어디에서 호출되는지에 따라 동작이 달라진다고 이해하면 될 것 같습니다. 

```java
public class Class1 {
    public static void doIt() {
        System.out.println("Class1.doIt");
    }

    public void doThat() {
        System.out.println("Class1.doThat");
    }
}

public class Class2 extends Class1 {

    public static void doIt() {
        System.out.println("Class2.doIt");
    }

    public void doThat() {
        System.out.println("Class2.doThat");
    }
}
```

```java
/**
 * case 1
 */ 
public class Main {
    public static void main(String[] args) {
        Class1 c1 = new Class1();
        Class1.doIt(); // Class1.doIt
        c1.doIt(); // Class1.doIt
    }
}

/**
 * case 2
 */ 
public class Main {
    public static void main(String[] args) {
        Class2 c2 = new Class2();
        Class2.doIt(); // Class2.doIt
        c2.doIt(); // Class2.doIt
    }
}

/**
 * case 3
 */
public class Main {
    public static void main(String[] args) {
        Class1 c = new Class2();
        c.doIt();  //Class1.doIt
        c.doThat(); //Class2.doThat
    }
}
```

oracle docs를 읽어보면, 

If a subclass defines a static method with the same signature as a static method in the superclass, then the method in the subclass *hides* the one in the superclass.

자식 클래스가 부모 클래스의 정적 메서드와 동일한 시그니처를 가진 정적 메서드를 정의하는 경우, 자식 클래스에서의 메서드는 부모 클래스의 메서드를 숨긴다. 

- The version of the overridden instance method that gets invoked is the one in the subclass.
- The version of the hidden static method that gets invoked depends on whether it is invoked from the superclass or the subclass.

호출된 재정의된 (overridden) 인스턴스의 메서드 버전은 자식 클래스의 버전이다.  
호출된 숨겨진 (hidden) 정적 메서드의 버전은 부모 클래스에서 호출되는지 아니면 자식 클래스에서 호출되는지에 따라 다르다. 

method hiding 이 일어나면 자식 클래스 인스턴스가 메서드를 호출할 경우 부모 클래스의 메서드가 호출됩니다.
런타임 시 인스턴스가 실제로 참조하고 있는 클래스를 찾아가는 것이 아니라 컴파일 시 결정된 클래스를 찾아가기 때문에 이와 같은 상황이 발생하는데요,  
어떤 메서드를 호출할지 결정하여 실제로 호출시키는 과정을 `메서드 디스패치`라고 합니다.   
자바는 런타임 시 객체를 생성하고, 컴파일 시에는 생성할 객체 타입에 대한 정보만 보유합니다.  
이 과정은 static (정적)과 dynamic (동적)으로 구분할 수 있습니다.   


정적 디스패치 : 컴파일 시점에서 컴파일러가 특정 메소드를 호출할 것이라고 명확하게 알고있는 경우  
동적 디스패치 : 정적 디스패치와 반대로 컴파일러가 어떤 메서드를 호출하는지 모르는 경우. 동적 디스패치는 호출할 메서드를 런타임 시점에서 결정한다.

오버라이딩이 `런타임 시점`에 이루어지는 동적 디스패치이고, static 은 `컴파일 시점`에 이루어지므로 애초에 런타임 시점이 오버라이딩과 어울릴 수 없습니다. 

또한 오버라이딩은 클래스의 객체에 달려있는데, 객체지향에서 오버라이딩의 포인트는 클래스를 자식 클래스화 할 수 있고, 자식 클래스의 객체는 부모 클래스의 동일한 메서드에 대해서 다른 동작을 하여 다형성을 보장하는 것입니다.   
반면 static 키워드를 사용한다면 하나를 공유하여 사용한다는 개념이므로 객체가 생성되기도 전에 미리 만들어져 있습니다.

**Comment by lllilllilllilili** [comment]
유리님 좋은 코멘트 감사해요. 
`오버라이딩`, `static` 에 대해 이제 조금 알것 같아요.

**Comment by java-saeng** [comment]
새로운 ㅇ
